### ISSUE TITLE
HorizontalLayout slot alignment breaks for buttons

### ISSUE THREAD

**Issue by stefanuebe** [juuso-vaadin/theme-development-starter#3]
The starpass theme overrides the margin for buttons. This breaks the alignment, when they are placed inside a horizontal layout using the new alignment slots (addToStart, etc.), which makes them all aligned left, despite their assigned slots.

![Image](https://github.com/user-attachments/assets/69dd173d-439f-49dd-ab5e-b8d587c8276a)

**Comment by stefanuebe** [comment]
Workaround: add this snippet to your theme styles.css (extend with other constellations if needed for you cases)

```css
vaadin-horizontal-layout[has-end]:not([has-middle]) [last-start-child] {
    margin-inline-end: auto;
}

vaadin-horizontal-layout[has-end]:not([has-middle]):not([has-middle]) [first-end-child] {
    margin-inline-start: auto;
}

/* ... */
```
